#env:
#  TERM: alacritty

window:
  padding:
    x: 0
    y: 0

  dynamic_padding: false
  decorations: full
  startup_mode: Fullscreen
  dynamic_title: true

scrolling:
  history: 50000
  multiplier: 1

font:
  normal:
    family: SF Mono
    style: Regular
  bold:
    family: SF Mono
    style: Bold
  size: 15.0
  offset:
    x: 0
    y: 0
  use_thin_strokes: true

draw_bold_text_with_bright_colors: true

live_config_reload: true

key_bindibngs:
  { key: S, mods: Shift|Option, mode: ~Search, action: ToggleViMode }

import:
  - ~/gruvbox/gruvbox.yml

