theme = "kinda_nvim"

[editor]
color-modes = true
# shell = ["zsh", "-c"]
shell = ["fish", "-c"]
line-number = "relative"
cursorline = true
completion-timeout = 50
preview-completion-insert = false
completion-trigger-len = 1
rulers = [80]
end-of-line-diagnostics = "hint"

[editor.statusline]
left =  ["file-name", "file-modification-indicator"]
right = ["workspace-diagnostics", "separator", "selections", "separator", "position", "position-percentage"]
workspace-diagnostics = ["error", "warning", "hint", "info"]

[editor.lsp]
auto-signature-help = false

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
nbsp = "all"
nnbsp = "all"

[editor.indent-guides]
render = true
# skip-levels = 1

[editor.gutters]
layout = ["diagnostics", "spacer", "line-numbers", "spacer", "diff", "spacer"]

[editor.soft-wrap]
enable = true

[editor.smart-tab]
supersede-menu = true

[editor.inline-diagnostics]
cursor-line = "hint"

[keys.normal]
C-y = "scroll_up"
C-e = "scroll_down"

[keys.normal.space]
w = ":write-all"
F = "file_picker_in_current_buffer_directory"
o = "file_explorer_in_current_buffer_directory"
O = "file_explorer_in_current_directory"
e = "no_op"
E = "no_op"

[keys.insert]
C-y = "scroll_up"
C-e = "scroll_down"
C-s = "signature_help"
