theme = "nightfox"

[editor]
cursorline = true
shell = ["zsh", "-c"]
line-number = "relative"
rulers = [80]
preview-completion-insert = false
popup-border = "none"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[keys.insert]
