theme = "default"

[editor]
shell = ["zsh", "-c"]
line-number = "relative"
cursorline = true
completion-timeout = 50
preview-completion-insert = false
completion-trigger-len = 1
rulers = [80]
end-of-line-diagnostics = "hint"

[editor.statusline]
left = ["mode", "version-control", "file-name", "file-modification-indicator"]
right = ["workspace-diagnostics", "selections", "position", "position-percentage"]

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
nbsp = "all"
nnbsp = "all"

# [editor.indent-guides]
# render = true

[editor.gutters]
layout = ["diagnostics", "spacer", "line-numbers", "spacer", "diff", "spacer"]

[editor.soft-wrap]
enable = true

[editor.smart-tab]
supersede-menu = true

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.normal]
C-y = "scroll_up"
C-e = "scroll_down"
S-k = "hover"

[keys.normal.space]
w = ":write-all"
F = "file_picker_in_current_buffer_directory"

[keys.insert]
C-y = "scroll_up"
C-e = "scroll_down"

