# [[language]]
# name = "gdscript"
# roots = ["project.godot"]
# language-server = { command = "nc", args = ["localhost", "6008"], language-id = "gdscript" }
 
[language-server.dartls]
command = "dart"
args = ["language-server", "--protocol=lsp"]
config = { closingLabels = true, outline = true, flutterOutline = true, dart = { showTodos = true, renameFilesWithClasses = "prompt" } }

[[language]]
name = "dart"
diagnostic-severity = "hint"
language-servers = ["dartls"]

[language-server.bashls]
command = "bunx"
args = ["--bun", "bash-language-server", "start"]

[language-server.biome]
command = "bunx"
args = ["--bun", "biome", "lsp-proxy"]

[language-server.cssls]
command = "bunx"
args = ["--bun", "vscode-css-language-server", "--stdio"]

[language-server.html]
command = "bunx"
args = ["--bun", "vscode-html-language-server", "--stdio"]

[language-server.jsonls]
command = "bunx"
args = ["--bun", "vscode-json-language-server", "--stdio"]

[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[language-server.svelte]
command = "bunx"
args = ["--bun", "svelteserver", "--stdio"]

[language-server.tailwindcss]
command = "bunx"
args = ["--bun", "tailwindcss-language-server", "--stdio"]

[language-server.typescript]
command = "bunx"
args = ["--bun", "typescript-language-server", "--stdio"]

[[language]]
name = "typescript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "javascript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "tsx"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "jsx"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[language-server.yamlls]
command = "bunx"
args = ["--bun", "yaml-language-server", "--stdio"]

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.rust-analyzer.config.cargo]
features = "all"
