set -g base-index 1
set -g mouse on
set -g mode-keys vi
set -sg escape-time 10
set -g focus-events on
set -g default-terminal "screen-256color"
set-option -sa terminal-overrides ',xterm-256color:RGB'

set -g clock-mode-colour "#654F94"
set -g status-style bg=#654F94,fg=white
set -g status-right '#{t/:session_activity}'
set -g status-justify
set -g status-interval 1


bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
