vim.cmd.highlight("clear")

if vim.g.syntax_on then
	vim.cmd.syntax("reset")
end

vim.cmd("highlight clear Search")
vim.cmd("highlight clear CurSearch")
vim.cmd("highlight clear Pmenu")
vim.cmd("highlight clear PmenuSel")
vim.cmd("highlight clear PmenuThumb")
vim.cmd("highlight clear MatchParen")
vim.cmd("highlight clear NormalFloat")
vim.cmd("highlight clear FloatBorder")

if vim.o.background == "dark" then
	vim.cmd("highlight Normal guifg=#D0D1D2 guibg=#0F0F10")
	vim.cmd("highlight NonText guifg=#4C4E5D")
	vim.cmd("highlight Comment gui=italic guifg=#B6AB96")
	vim.cmd("highlight Title guifg=#D0D1D2 gui=bold")
	vim.cmd("highlight Directory guifg=#439FB1")
	vim.cmd("highlight ErrorMsg guifg=#E09085")
	vim.cmd("highlight WarningMsg guifg=#E0C685")
	vim.cmd("highlight ModeMsg guifg=#75BD7F")
	vim.cmd("highlight Search guibg=#383A3E")
	vim.cmd("highlight CurSearch guibg=#505862")
	vim.cmd("highlight CursorLine guibg=#1E1E1F")
	vim.cmd("highlight Visual guibg=#383A3E")
	vim.cmd("highlight Folded guifg=#7A7F85 guibg=#1E1E1F")
	vim.cmd("highlight DiffAdd guifg=#9CC9BC guibg=#2C492C")
	vim.cmd("highlight DiffChange guibg=#2C2E30")
	vim.cmd("highlight DiffDelete guifg=#E09085 guibg=#5C3833")
	vim.cmd("highlight SpellBad cterm=undercurl gui=undercurl guisp=#E09085")
	vim.cmd("highlight SpellCap cterm=undercurl gui=undercurl guisp=#E0C685")
	vim.cmd("highlight SpellRare cterm=undercurl gui=undercurl guisp=#439FB1")
	vim.cmd("highlight SpellLocal cterm=undercurl gui=undercurl guisp=#85B1D1")
	vim.cmd("highlight Pmenu guifg=#A9ABAD guibg=#1E1E1F")
	vim.cmd("highlight PmenuSel guibg=#2C2E30")
	vim.cmd("highlight Type guifg=#51BD99")
	vim.cmd("highlight Statement gui=NONE guifg=#BD75A5")
	vim.cmd("highlight Identifier guifg=#85B1D1")
	vim.cmd("highlight Constant gui=bold guifg=#85B1D1")
	vim.cmd("highlight @variable guifg=#D0D1D2 guibg=NONE")
	vim.cmd("highlight String guifg=#8F9193")
	vim.cmd("highlight Number guifg=#E09085")
	vim.cmd("highlight Delimiter guifg=#A9ABAD")
	vim.cmd("highlight DaignosticDeprecated gui=strikethrough guisp=#E09085")
	vim.cmd("highlight FloatBorder gui=NONE guifg=NONE guibg=#1E1E1F")
	vim.cmd("highlight FloatShadow guibg=#4C4E5D blend=80")
	vim.cmd("highlight FloatShadowThrough guibg=#4C4E5D blend=100")
	vim.cmd("highlight ColorColumn guibg=#1E1E1F")

	-- blink
	vim.cmd("highlight BlinkCmpLabelMatch gui=bold guifg=#D0D1D2")

	-- fzf lua
	vim.cmd("highlight FzfLuaFzfMatch gui=bold guifg=#D0D1D2")
	vim.cmd("highlight FzfLuaBorder guifg=#1E1E1F guibg=#1E1E1F")
	vim.cmd("highlight FzfLuaTitle gui=bold guifg=#D0D1D2 guibg=#1E1E1F")
	vim.cmd("highlight FzfLuaPreviewBorder guifg=#0F0F10 guibg=#0F0F10")
	vim.cmd("highlight FzfLuaFzfCursorLine guifg=#D0D1D2 guibg=#2C2E30")
else
	vim.cmd("highlight Normal guifg=#18191B guibg=#ECEDEE")
	vim.cmd("highlight NonText guifg=#BCBFC2")
	vim.cmd("highlight Comment gui=italic guifg=#9B8C6F")
	vim.cmd("highlight Title guifg=#18191B gui=bold")
	vim.cmd("highlight Directory guifg=#006F85")
	vim.cmd("highlight ErrorMsg guifg=#C43B27")
	vim.cmd("highlight WarningMsg guifg=#BD8600")
	vim.cmd("highlight ModeMsg guifg=#008F00")
	vim.cmd("highlight Search guibg=#DCDDE0")
	vim.cmd("highlight CurSearch guibg=#C9CBCF")
	vim.cmd("highlight CursorLine guibg=#E4E5E7")
	vim.cmd("highlight Visual guibg=#DCDDE0")
	vim.cmd("highlight Folded guifg=#505862 guibg=#E4E5E7")
	vim.cmd("highlight DiffAdd guifg=#1D721D guibg=#CFE2CF")
	vim.cmd("highlight DiffChange guibg=#F7F7F8")
	vim.cmd("highlight DiffDelete guifg=#C43B27 guibg=#E8DBD9")
	vim.cmd("highlight SpellBad cterm=undercurl gui=undercurl guisp=#C43B27")
	vim.cmd("highlight SpellCap cterm=undercurl gui=undercurl guisp=#BD8600")
	vim.cmd("highlight SpellRare cterm=undercurl gui=undercurl guisp=#006F85")
	vim.cmd("highlight SpellLocal cterm=undercurl gui=undercurl guisp=#306F9C")
	vim.cmd("highlight Pmenu guifg=#55595E guibg=#E4E5E7")
	vim.cmd("highlight PmenuSel guibg=#F7F7F8")
	vim.cmd("highlight Type guifg=#008055")
	vim.cmd("highlight Statement gui=NONE guifg=#9E2E79")
	vim.cmd("highlight Identifier guifg=#306F9C")
	vim.cmd("highlight Constant gui=bold guifg=#306F9C")
	vim.cmd("highlight @variable guifg=#18191B")
	vim.cmd("highlight String guifg=#6C7179")
	vim.cmd("highlight Number guifg=#C43B27")
	vim.cmd("highlight Delimiter guifg=#55595E")
	vim.cmd("highlight DaignosticDeprecated gui=strikethrough guisp=#C43B27")
	vim.cmd("highlight FloatBorder gui=NONE guifg=NONE guibg=#E4E5E7")
	vim.cmd("highlight FloatShadow guibg=#BCBFC2 blend=80")
	vim.cmd("highlight FloatShadowThrough guibg=#BCBFC2 blend=100")
	vim.cmd("highlight ColorColumn guibg=#E4E5E7")

	-- blink
	vim.cmd("highlight BlinkCmpLabelMatch gui=bold guifg=#18191B")

	-- fzf lua
	vim.cmd("highlight FzfLuaFzfMatch gui=bold guifg=#18191B")
	vim.cmd("highlight FzfLuaBorder guifg=#E4E5E7 guibg=#E4E5E7")
	vim.cmd("highlight FzfLuaTitle gui=bold guifg=#18191B guibg=#E4E5E7")
	vim.cmd("highlight FzfLuaPreviewBorder guifg=#ECEDEE guibg=#ECEDEE")
	vim.cmd("highlight FzfLuaFzfCursorLine guifg=#18191B guibg=#F7F7F8")
end

vim.cmd("highlight Todo gui=bold")

vim.cmd("highlight! link IncSearci CurSearch")
vim.cmd("highlight! link LineNr NonText")
vim.cmd("highlight! link LineNrAbove LineNr")
vim.cmd("highlight! link LineNrBelow LineNr")
vim.cmd("highlight! link SignColumn NonText")
vim.cmd("highlight! link Conceal NonText")
vim.cmd("highlight! link CursorColumn CursorLine")
vim.cmd("highlight! link CursorLineNr CursorLine")
vim.cmd("highlight! link CursorLineSign CursorLine")
vim.cmd("highlight! link CursorLineFold CursorLine")
vim.cmd("highlight! link MoreMsg Directory")
vim.cmd("highlight! link Question Directory")
vim.cmd("highlight! link QuickFixLine Directory")
vim.cmd("highlight! link StatusLine Normal")
vim.cmd("highlight! link StatusLineNC NonText")
vim.cmd("highlight! link MsgSeparator StatusLine")
vim.cmd("highlight! link WinSeparator NonText")
vim.cmd("highlight! link VertSplit WinSeparator")
vim.cmd("highlight! link FoldColumn NonText")
vim.cmd("highlight! link DiffText CurSearch")
vim.cmd("highlight! link PmenuThumb Visual")
vim.cmd("highlight! link NormalFloat Pmenu")
vim.cmd("highlight! link Special Directory")
vim.cmd("highlight! link Operator Delimiter")
vim.cmd("highlight! link Function Directory")
vim.cmd("highlight! link PreProc Statement")
vim.cmd("highlight! link DiagnosticError ErrorMsg")
vim.cmd("highlight! link DiagnosticWarn WarningMsg")
vim.cmd("highlight! link DiagnosticInfo MoreMsg")
vim.cmd("highlight! link DiagnosticHint Identifier")
vim.cmd("highlight! link DiagnosticOk DiagnosticInfo")
vim.cmd("highlight! link Added DiffAdd")
vim.cmd("highlight! link Changed DiffChange")
vim.cmd("highlight! link Removed DiffDelete")
vim.cmd("highlight! link MatchParen Visual")
vim.cmd("highlight! link DiagnosticUnderlineError SpellBad")
vim.cmd("highlight! link DiagnosticUnderlineWarn SpellCap")
vim.cmd("highlight! link DiagnosticUnderlineInfo SpellRare")
vim.cmd("highlight! link DiagnosticUnderlineHint SpellLocal")
vim.cmd("highlight! link DiagnosticUnderlineOk DiagnosticUnderlineHint")

-- lsp
vim.cmd("highlight! link @lsp.type.comment Comment")
vim.cmd("highlight! link @lsp.type.enum Type")
vim.cmd("highlight! link @lsp.type.enumMember Constant")
vim.cmd("highlight! link @lsp.type.escapeSequence Delimiter")
vim.cmd("highlight! link @lsp.type.formatSpecifier Operator")
vim.cmd("highlight! link @lsp.type.namespace Type")
vim.cmd("highlight! link @lsp.type.operator Operator")
vim.cmd("highlight! link @lsp.type.parameter Identifier")
vim.cmd("highlight! link @lsp.type.property Identifier")
vim.cmd("highlight! link @lsp.type.variable @variable")
vim.cmd("highlight! link @lsp.typemod.variable.constant Constant")
vim.cmd("highlight! link @lsp.typemod.keyword.controlFlow Delimiter")

-- blink
vim.cmd("highlight! link BlinkCmpMenu Pmenu")
vim.cmd("highlight! link BlinkCmpMenuBorder Pmenu")
vim.cmd("highlight! link BlinkCmpMenuSelection PmenuSel")
vim.cmd("highlight! link BlinkCmpScrollBarThumb PmenuThumb")
vim.cmd("highlight! link BlinkCmpScrollBarGutter PmenuSbar")
-- vim.cmd("highlight! BlinkCmpLabel Pmenu")
vim.cmd("highlight! link BlinkCmpLabelDeprecated DaignosticDeprecated")
vim.cmd("highlight! link BlinkCmpGhostText NonText")
vim.cmd("highlight! link BlinkCmpKind Type")
vim.cmd("highlight! link BlinkCmpKindText String")
vim.cmd("highlight! link BlinkCmpKindMethod Function")
vim.cmd("highlight! link BlinkCmpKindFunction Function")
vim.cmd("highlight! link BlinkCmpKindConstructor Function")
vim.cmd("highlight! link BlinkCmpKindField Identifier")
vim.cmd("highlight! link BlinkCmpKindVariable Identifier")
vim.cmd("highlight! link BlinkCmpKindClass Type")
vim.cmd("highlight! link BlinkCmpKindInterface Type")
vim.cmd("highlight! link BlinkCmpKindModule Function")
vim.cmd("highlight! link BlinkCmpKindProperty Identifier")
vim.cmd("highlight! link BlinkCmpKindUnit Structure")
vim.cmd("highlight! link BlinkCmpKindValue Constant")
vim.cmd("highlight! link BlinkCmpKindEnum Constant")
vim.cmd("highlight! link BlinkCmpKindKeyword Keyword")
vim.cmd("highlight! link BlinkCmpKindSnippet Special")
vim.cmd("highlight! link BlinkCmpKindColor Label")
vim.cmd("highlight! link BlinkCmpKindFile Directory")
vim.cmd("highlight! link BlinkCmpKindReference StorageClass")
vim.cmd("highlight! link BlinkCmpKindFolder Directory")
vim.cmd("highlight! link BlinkCmpKindEnumMember Constant")
vim.cmd("highlight! link BlinkCmpKindConstant Constant")
vim.cmd("highlight! link BlinkCmpKindStruct Structure")
vim.cmd("highlight! link BlinkCmpKindEvent Repeat")
vim.cmd("highlight! link BlinkCmpKindOperator Operator")
vim.cmd("highlight! link BlinkCmpKindTypeParameter Type")
vim.cmd("highlight! link BlinkCmpSource NonText")
vim.cmd("highlight! link BlinkCmpDoc NormalFloat")
vim.cmd("highlight! link BlinkCmpDocBorder NormalFloat")
vim.cmd("highlight! link BlinkCmpDocCursorLine CursorLine")
vim.cmd("highlight! link BlinkCmpSignatureHelp NormalFloat")
vim.cmd("highlight! link BlinkCmpSignatureHelpBorder NormalFloat")
vim.cmd("highlight! link BlinkCmpSignatureHelpActiveParameter LspSignatureActiveParameter")

-- fzf lua
vim.cmd("highlight! link FzfLuaNormal Pmenu")
vim.cmd("highlight! link FzfLuaPreviewNormal Normal")
vim.cmd("highlight! link FzfLuaPreviewTitle Title")
vim.cmd("highlight! link FzfLuaCursorLineNr CursorLineNr")
vim.cmd("highlight! link FzfLuaScrollBorderFull PmenuThumb")
vim.cmd("highlight! link FzfLuaScrollBorderEmpty Pmenu")
vim.cmd("highlight! link FzfLuaScrollFloatFull FzfLuaScrollBorderFull")
vim.cmd("highlight! link FzfLuaScrollFloatEmpty FzfLuaScrollBorderEmpty")
vim.cmd("highlight! link FzfLuaHeaderBind ModeMsg")
vim.cmd("highlight! link FzfLuaHeaderText NonText")
vim.cmd("highlight! link FzfLuaPathLineNr NonText")
vim.cmd("highlight! link FzfLuaPathColNr NonText")
vim.cmd("highlight! link FzfLuaBufName WarningMsg")
vim.cmd("highlight! link FzfLuaBufNr NonText")
vim.cmd("highlight! link FzfLuaBufFlagCur Identifier")
vim.cmd("highlight! link FzfLuaBufFlagAlt ModeMsg")
vim.cmd("highlight! link FzfLuaTabTitle FzfLuaTitle")
vim.cmd("highlight! link FzfLuaTabMarker ModeMsg")
vim.cmd("highlight! link FzfLuaLiveSym NormalFloat")
vim.cmd("highlight! link FzfLuaFzfHeader NormalFloat")
vim.cmd("highlight! link FzfLuaFzfScrollbar PmenuSbar")
vim.cmd("highlight! link FzfLuaFzfSeparator NormalFloat")
vim.cmd("highlight! link FzfLuaFzfGutter Pmenu")
vim.cmd("highlight! link FzfLuaFzfPointer Identifier")
vim.cmd("highlight! link FzfLuaFzfMarker Identifier")
vim.cmd("highlight! link FzfLuaFzfPrompt Identifier")
vim.cmd("highlight! link FzfLuaFzfQuery NormalFloat")



vim.g.colors_name = "default_but_better"
