vim.cmd.highlight("clear")

if vim.g.syntax_on then
	vim.cmd.syntax("reset")
end

vim.cmd("highlight clear Pmenu")
vim.cmd("highlight clear PmenuSel")
vim.cmd("highlight clear PmenuThumb")
vim.cmd("highlight clear MatchParen")
vim.cmd("highlight clear NormalFloat")
vim.cmd("highlight clear FloatBorder")

if vim.o.background == "dark" then
	vim.cmd("highlight Normal guifg=#B9BBC6 guibg=#1A1E1D")
	-- vim.cmd("highlight NonText guifg=#B9BBC6 guibg=#1A1E1D")
	vim.cmd("highlight Title guibg=#B9BBC6 gui=bold")
	vim.cmd("highlight Directory guifg=#40BEBF")
	vim.cmd("highlight ErrorMsg guifg=#E49F95")
	vim.cmd("highlight Search guifg=#C9CACF guibg=#1F4747")
	vim.cmd("highlight CurSearch guifg=#D7D8DB guibg=#2A6F58")
else
	vim.cmd("highlight Normal guifg=#232A28 guibg=#ECEEEE")
	vim.cmd("highlight NonText guifg=#A9BCB9")
	vim.cmd("highlight Comment gui=italic guifg=#8A8A56")
	vim.cmd("highlight Title guifg=#232A28 gui=bold")
	vim.cmd("highlight Directory guifg=#2991A3")
	vim.cmd("highlight ErrorMsg guifg=#DC3218")
	vim.cmd("highlight WarningMsg guifg=#BD8600")
	vim.cmd("highlight ModeMsg guifg=#008F00")
	vim.cmd("highlight Search guifg=#232A28 guibg=#C3DFDA")
	vim.cmd("highlight CurSearch guifg=#232A28 guibg=#7ECEC1")
	vim.cmd("highlight CursorLine guibg=#DDE3E3")
	vim.cmd("highlight Visual guibg=#CDD6D6")
	vim.cmd("highlight Folded guifg=#4C6762 guibg=#E0E6E6")
	vim.cmd("highlight DiffAdd guifg=#232A28 guibg=#ADDCAD")
	vim.cmd("highlight DiffChange guifg=#171C1B guibg=#CDD6D6")
	vim.cmd("highlight DiffDelete guifg=#CC4733 guibg=#F7D4CF")
	vim.cmd("highlight SpellBad cterm=undercurl gui=undercurl guisp=#CC4733")
	vim.cmd("highlight SpellCap cterm=undercurl gui=undercurl guisp=#C39422")
	vim.cmd("highlight SpellRare cterm=undercurl gui=undercurl guisp=#327632")
	vim.cmd("highlight SpellLocal cterm=undercurl gui=undercurl guisp=#246FA8")
	vim.cmd("highlight Pmenu guibg=#F7F8F8")
	vim.cmd("highlight PmenuSel guibg=#ECEEEE")
	vim.cmd("highlight Type guifg=#008F77")
	vim.cmd("highlight Statement gui=NONE guifg=#2B8000")
	vim.cmd("highlight Identifier guifg=#2471A8")
	vim.cmd("highlight Number guifg=#CC4733")
	vim.cmd("highlight Delimiter guifg=#232A28")
	vim.cmd("highlight @variable guifg=#232A28")
	vim.cmd("highlight Todo gui=bold guifg=#232A28")
	vim.cmd("highlight DaignosticDeprecated gui=strikethrough guisp=#CC4733")
	vim.cmd("highlight FloatBorder gui=NONE guifg=NONE guibg=#F7F8F8")
	vim.cmd("highlight FloatShadow guibg=#A9BCB9 blend=80")
	vim.cmd("highlight FloatShadowThrough guibg=#A9BCB9 blend=100")

	-- fzf lue
	vim.cmd("highlight FzfLuaBorder guifg=#F7F8F8 guibg=#F7F8F8")
	vim.cmd("highlight FzfLuaTitle gui=bold guifg=#232A28 guibg=#F7F8F8")
	vim.cmd("highlight FzfLuaPreviewBorder guifg=#ECEEEE guibg=#ECEEEE")
	vim.cmd("highlight FzfLuaFzfCursorLine guifg=#232A28 guibg=#ECEEEE")
end

vim.cmd("highlight! link IncSearci CurSearch")
vim.cmd("highlight! link LineNr NonText")
vim.cmd("highlight! link LineNrAbove LineNr")
vim.cmd("highlight! link LineNrBelow LineNr")
vim.cmd("highlight! link SignColumn NonText")
vim.cmd("highlight! link ColorColumn NonText")
vim.cmd("highlight! link Conceal NonText")
vim.cmd("highlight! link CursorColumn CursorLine")
vim.cmd("highlight! link CursorLineNr Normal")
vim.cmd("highlight! link CursorLineSign SignColumn")
vim.cmd("highlight! link CursorLineFold FoldColumn")
vim.cmd("highlight! link MoreMsg Directory")
vim.cmd("highlight! link Question Directory")
vim.cmd("highlight! link QuickFixLine Directory")
vim.cmd("highlight! link StatusLine Normal")
vim.cmd("highlight! link StatusLineNC NonText")
vim.cmd("highlight! link MsgSeparator StatusLine")
vim.cmd("highlight! link WinSeparator NonText")
vim.cmd("highlight! link VertSplit WinSeparator")
vim.cmd("highlight! link FoldColumn NonText")
vim.cmd("highlight! link DiffText CurSearch")
vim.cmd("highlight! link PmenuThumb Visual")
vim.cmd("highlight! link NormalFloat Pmenu")
vim.cmd("highlight! link Special Directory")
vim.cmd("highlight! link Operator Delimeter")
vim.cmd("highlight! link Function Directory")
vim.cmd("highlight! link String ModeMsg")
vim.cmd("highlight! link DiagnosticError ErrorMsg")
vim.cmd("highlight! link DiagnosticWarn WarningMsg")
vim.cmd("highlight! link DiagnosticInfo MoreMsg")
vim.cmd("highlight! link DiagnosticHint Identifier")
vim.cmd("highlight! link DiagnosticOk DiagnosticInfo")
vim.cmd("highlight! link Added DiffAdd")
vim.cmd("highlight! link Changed DiffChange")
vim.cmd("highlight! link Removed DiffDelete")
vim.cmd("highlight! link MatchParen Visual")
vim.cmd("highlight! link DiagnosticUnderlineError SpellBad")
vim.cmd("highlight! link DiagnosticUnderlineWarn SpellCap")
vim.cmd("highlight! link DiagnosticUnderlineInfo SpellRare")
vim.cmd("highlight! link DiagnosticUnderlineHint SpellLocal")
vim.cmd("highlight! link DiagnosticUnderlineOk DiagnosticUnderlineHint")

-- vim.cmd("highlight! link @lsp.type.comment")
vim.cmd("highlight! link @lsp.type.enum Type")
vim.cmd("highlight! link @lsp.type.enumMember Constant")
-- vim.cmd("highlight! link @lsp.type.escapeSequence")
vim.cmd("highlight! link @lsp.type.formatSpecifier Operator")
vim.cmd("highlight! link @lsp.type.namespace Type")
vim.cmd("highlight! link @lsp.type.operator Operator")
-- vim.cmd("highlight! link @lsp.type.parameter")
vim.cmd("highlight! link @lsp.type.property Normal")
-- vim.cmd("highlight! link @lsp.type.variable")
vim.cmd("highlight! link @lsp.typemod.variable.constant Constant")
-- vim.cmd("highlight! link @lsp.typemod.keyword.controlFlow")

-- blink
vim.cmd("highlight! link BlinkCmpMenu Pmenu")
vim.cmd("highlight! link BlinkCmpMenuBorder Pmenu")
vim.cmd("highlight! link BlinkCmpMenuSelection PmenuSel")
vim.cmd("highlight! link BlinkCmpScrollBarThumb PmenuThumb")
vim.cmd("highlight! link BlinkCmpScrollBarGutter PmenuSbar")
-- vim.cmd("highlight! BlinkCmpLabel Pmenu")
vim.cmd("highlight! link BlinkCmpLabelDeprecated DaignosticDeprecated")
vim.cmd("highlight! link BlinkCmpLabelMatch Folded")
vim.cmd("highlight! link BlinkCmpGhostText NonText")
vim.cmd("highlight! link BlinkCmpKind Type")
vim.cmd("highlight! link BlinkCmpKindText String")
vim.cmd("highlight! link BlinkCmpKindMethod Function")
vim.cmd("highlight! link BlinkCmpKindFunction Function")
vim.cmd("highlight! link BlinkCmpKindConstructor Function")
vim.cmd("highlight! link BlinkCmpKindField Identifier")
vim.cmd("highlight! link BlinkCmpKindVariable Identifier")
vim.cmd("highlight! link BlinkCmpKindClass Type")
vim.cmd("highlight! link BlinkCmpKindInterface Type")
vim.cmd("highlight! link BlinkCmpKindModule Function")
vim.cmd("highlight! link BlinkCmpKindProperty Identifier")
vim.cmd("highlight! link BlinkCmpKindUnit Structure")
vim.cmd("highlight! link BlinkCmpKindValue Constant")
vim.cmd("highlight! link BlinkCmpKindEnum Constant")
vim.cmd("highlight! link BlinkCmpKindKeyword Keyword")
vim.cmd("highlight! link BlinkCmpKindSnippet Special")
vim.cmd("highlight! link BlinkCmpKindColor Label")
vim.cmd("highlight! link BlinkCmpKindFile Directory")
vim.cmd("highlight! link BlinkCmpKindReference StorageClass")
vim.cmd("highlight! link BlinkCmpKindFolder Directory")
vim.cmd("highlight! link BlinkCmpKindEnumMember Constant")
vim.cmd("highlight! link BlinkCmpKindConstant Constant")
vim.cmd("highlight! link BlinkCmpKindStruct Structure")
vim.cmd("highlight! link BlinkCmpKindEvent Repeat")
vim.cmd("highlight! link BlinkCmpKindOperator Operator")
vim.cmd("highlight! link BlinkCmpKindTypeParameter Type")
vim.cmd("highlight! link BlinkCmpSource NonText")
vim.cmd("highlight! link BlinkCmpDoc NormalFloat")
vim.cmd("highlight! link BlinkCmpDocBorder NormalFloat")
vim.cmd("highlight! link BlinkCmpDocCursorLine CursorLine")
vim.cmd("highlight! link BlinkCmpSignatureHelp NormalFloat")
vim.cmd("highlight! link BlinkCmpSignatureHelpBorder NormalFloat")
vim.cmd("highlight! link BlinkCmpSignatureHelpActiveParameter LspSignatureActiveParameter")

-- fzf lua
vim.cmd("highlight! link FzfLuaNormal Pmenu")
vim.cmd("highlight! link FzfLuaPreviewNormal Normal")
vim.cmd("highlight! link FzfLuaPreviewTitle Title")
vim.cmd("highlight! link FzfLuaCursorLineNr CursorLineNr")
vim.cmd("highlight! link FzfLuaScrollBorderFull PmenuThumb")
vim.cmd("highlight! link FzfLuaScrollBorderEmpty Pmenu")
vim.cmd("highlight! link FzfLuaScrollFloatFull FzfLuaScrollBorderFull")
vim.cmd("highlight! link FzfLuaScrollFloatEmpty FzfLuaScrollBorderEmpty")
vim.cmd("highlight! link FzfLuaHeaderBind ModeMsg")
vim.cmd("highlight! link FzfLuaHeaderText NonText")
vim.cmd("highlight! link FzfLuaPathLineNr NonText")
vim.cmd("highlight! link FzfLuaPathColNr NonText")
vim.cmd("highlight! link FzfLuaBufName WarningMsg")
vim.cmd("highlight! link FzfLuaBufNr NonText")
vim.cmd("highlight! link FzfLuaBufFlagCur Identifier")
vim.cmd("highlight! link FzfLuaBufFlagAlt ModeMsg")
vim.cmd("highlight! link FzfLuaTabTitle FzfLuaTitle")
vim.cmd("highlight! link FzfLuaTabMarker ModeMsg")
vim.cmd("highlight! link FzfLuaLiveSym NormalFloat")
vim.cmd("highlight! link FzfLuaFzfHeader NormalFloat")
vim.cmd("highlight! link FzfLuaFzfMatch Folded")
vim.cmd("highlight! link FzfLuaFzfScrollbar PmenuSbar")
vim.cmd("highlight! link FzfLuaFzfSeparator NormalFloat")
vim.cmd("highlight! link FzfLuaFzfGutter Pmenu")
vim.cmd("highlight! link FzfLuaFzfPointer Pmenu")
vim.cmd("highlight! link FzfLuaFzfMarker Identifier")
vim.cmd("highlight! link FzfLuaFzfPrompt Pmenu")
vim.cmd("highlight! link FzfLuaFzfQuery NormalFloat")



vim.g.colors_name = "default_but_better"
